### ISSUE TITLE
response headers are not coming back

### ISSUE THREAD

**Issue by aravindnet** [xizmark/Webber#1]
i could not able to get response header in webberresponse.

**Comment by rahulrumalla** [comment]
Hey, there. What exactly are you trying to do and expect ? 

Do share the code if you can, please.

**Comment by rahulrumalla** [comment]
Yes, the WebberReponse does not currently expose any raw headers from the server. What is your use-case?

**Comment by aravindnet** [comment]
I am calling third party api and getting results. That 3rd party api gives
some data in response headers. iam trying to get that response headers

Thanks
Aravind

**Comment by rahulrumalla** [comment]
NuGet version 1.1.1 is pushed out with the response headers.
